{% set name = "anyconfig" %}
{% set version = 0.9.10 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e1674d184e5d9e56aad5321ee65612abaa7a05a03081ccf2ee452b2d557aeed

build:
  number: 0
  noarch: python
  entry_points:
    - anyconfig_cli = anyconfig.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools

test:
  imports:
    - anyconfig
    - anyconfig.backend
  commands:
    - pip check
    - anyconfig_cli --help
  requires:
    - pip

about:
  home: https://github.com/ssato/python-anyconfig
  summary: Library provides common APIs to load and dump configuration files in various formats
  doc_url: https://pythonhosted.org/anyconfig/
  license: MIT
  license_file: LICENSE.MIT

extra:
  recipe-maintainers:
    - knightdave
