{% set name = "applicationinsights" %}
{% set version = 0.11.9 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30a11aafacea34f8b160fbdc35254c9029c7e325267874e3c68f6bdbcd6ed2c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - applicationinsights
    - applicationinsights.channel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Microsoft/ApplicationInsights-Python
  summary: This project extends the Application Insights API surface to support Python.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - andreyz4k
