{% set name = "click_config_file" %}
{% set version = 0.6.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ded6ec1a73c41280727ec9c06031e929cdd8a5946bf0f99c0c3db3a71793d515

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - click >=6.7
    - configobj >=5.0.6
    - python

test:
  imports:
    - click_config_file
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/phha/click_config_file
  summary: Configuration file support for click applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ltalirz
    - phha
