{% set name = "colcon-pkg-config" %}
{% set version = 0.1.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81fc46d037159030ba7b23970c573a31cead315f3c2410101a3cec858ec6bfa3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - colcon-core
    - python

test:
  imports:
    - colcon_pkg_config
    - colcon_pkg_config.environment
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon adding an environment variable to find pkg-config files.
  license: AFL-2.0
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
