{% set name = "composeml" %}
{% set version = 0.5.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/composeml-{{ version }}.tar.gz
  sha256: cb17ce18094459254a0ee81bbed9805f05817b90ba7fdf533a2af4c770694a15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.0.2,<3.3.0
    - numpy >=1.13.3
    - pandas >=0.23.0
    - python >=3.6
    - seaborn >=0.9.0
    - tqdm >=4.19.2

test:
  imports:
    - composeml
    - composeml.data_slice
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://compose.alteryx.com
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeff-hernandez
