{% set name = "composeml" %}
{% set version = 0.4.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b405d781dbc38c23e6cff4cbc8cd378b51e06beec63981f873605b6f72521c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.0.2
    - numpy >=1.13.3
    - pandas >=0.23.0
    - python >=3.6
    - seaborn >=0.9.0
    - tqdm >=4.19.2

test:
  imports:
    - composeml
    - composeml.demos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://compose.featurelabs.com
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeff-hernandez
