{% set name = "conda-workon" %}
{% set version = 0.4.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f94909c703f2fa39c1f4830808205ba8f1303960bfb85687bd5fb7cc0580e1f

build:
  number: 0
  noarch: python
  entry_points:
    - conda-workon = conda_workon:main_workon
    - conda-worktmp = conda_workon:main_tmp
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - conda
    - python

test:
  imports:
    - conda_workon
  commands:
    - pip check
    - conda-workon --help
    - conda-worktmp --help
  requires:
    - pip

about:
  home: https://bitbucket.org/flub/conda-workon
  summary: Activate conda environments in subshells
  license: BSD-1-Clause
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - pmlandwehr
    - flub
