{% set name = "conda-press" %}
{% set version = 0.0.6 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccbbc5251eb0d7da26644ee72470c84ed3671e5bc839353fdea53eabaacee7c4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - lazyasd
    - python >=3.6
    - requests
    - ruamel.yaml
    - tqdm
    - xonsh

test:
  imports:
    - conda_press
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/regro/conda-press
  summary: Press conda packages into wheels
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scopatz
    - marcelotrevisani
