{% set name = "conda-docker" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conda-docker-{{ version }}.tar.gz
  sha256: 2a9fc6fecd486e1f425dbd8ba85ec55650448fa9714b5e7e0241a48479c11d41

build:
  number: 0
  noarch: python
  entry_points:
    - conda-docker=conda_docker.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - conda_docker
    - conda_docker.docker
  commands:
    - pip check
    - conda-docker --help
  requires:
    - pip

about:
  home: https://github.com/regro/conda-docker
  summary: Create minimal docker images from conda environments
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scopatz
