{% set name = "conda_deps" %}
{% set version = 0.0.9 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d12567fe9719befaa571c6167fff043338552399c5076910e5022e12bfd02c53

build:
  number: 0
  noarch: python
  entry_points:
    - conda_deps=conda_deps.conda_deps:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - conda_deps
  commands:
    - pip check
    - conda_deps --help
  requires:
    - pip

about:
  home: https://github.com/cgat-developers/conda-deps
  summary: Generate conda environment files from Python source code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sebastian-luna-valero
