{% set name = "configparser" %}
{% set version = 5.0.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ca44140ee259b5e3d8aaf47c79c36a7ab0d5e94d70bd4105c03ede7a20ea5a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm >=3.4.1
  run:
    - python >=3.6

test:
  imports:
    - backports
    - backports.configparser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/configparser/
  summary: Updated configparser from Python 3.8 for Python 2.6+.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
