{% set name = "configs" %}
{% set version = 3.0.3 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5ab09e04e441dac6aa856a71fbf5ffc62954352630f79d311b8f8a31d9ce19c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - configs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/moigagoo/configs
  summary: Configuration for humans
  doc_url: https://pythonhosted.org/configs/
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - dpryan79
