{% set name = "configargparse" %}
{% set version = 1.2.3 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edd17be986d5c1ba2e307150b8e5f5107aba125f3574dddd02c85d5cdcfd37dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - coverage
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - configargparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bw2/ConfigArgParse
  summary: A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msarahan
    - bollwyvl
