{% set name = "django-rest-swagger" %}
{% set version = 2.2.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48f6aded9937e90ae7cbe9e6c932b9744b8af80cc4e010088b3278c700e0685b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - coreapi >=2.3.0
    - djangorestframework >=3.5.4
    - openapi-codec >=1.3.1
    - python
    - simplejson

test:
  imports:
    - rest_framework_swagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marcgibbons/django-rest-swagger
  summary: Swagger UI for Django REST Framework 3.5+
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
