{% set name = "django-configurations" %}
{% set version = "2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-configurations-{{ version }}.tar.gz
  sha256: 9e3bcea1355ac50a4c9f854f751d214cb17e5f8adf18405a4488d0a1e8945915

build:
  number: 0
  noarch: python
  entry_points:
    - django-cadmin = configurations.management:execute_from_command_line
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python
    - six

test:
  imports:
    - configurations
  commands:
    - pip check
    - django-cadmin --help
  requires:
    - pip

about:
  home: https://django-configurations.readthedocs.io/
  summary: A helper for organizing Django settings.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
