{% set name = "django-configurations" %}
{% set version = 2.1 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71d9acdff33aa034f0157b0b3d23629fe0cd499bf4d0b6d699b9ca0701d952e8

build:
  number: 0
  noarch: python
  entry_points:
    - django-cadmin = configurations.management:execute_from_command_line
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - configurations
  commands:
    - pip check
    - django-cadmin --help
  requires:
    - pip

about:
  home: https://django-configurations.readthedocs.io/
  summary: A helper for organizing Django settings.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
