{% set name = "easybuild-easyconfigs" %}
{% set version = 3.9.3 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ffe31e459e14c3c429d4c55718da678f66fdee5691752d0ca5a1106086d42f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - easybuild_easyconfigs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://easybuilders.github.io/easybuild/
  summary: Easyconfig files are simple build specification files for EasyBuild, that specify the build parameters for software packages (version, compiler toolchain, dependency versions, etc.).
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jerowe
    - boegel
