{% set name = "flask-swagger" %}
{% set version = 0.2.13 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42420efbed1aad86f7ca6bb869df550e09591e1d540ebd3040c197906c0f0be6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - flask >=0.10
    - python
    - pyyaml >=3.0

test:
  imports:
    - flask_swagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gangverk/flask-swagger
  summary: Extract swagger specs from your flask project
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
    - xylar
