{% set name = "flask-restful-swagger" %}
{% set version = 0.20.2 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 216150fa690e672a364625f2f9d35d6771bc9b57461f1a7d690e5bad284e7dd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - flask-restful >=0.3.6
    - jinja2 >=2.10.1,<3.0.0
    - python

test:
  imports:
    - flask_restful_swagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rantav/flask-restful-swagger
  summary: Extract swagger specs from your flask-restful project
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
