{% set name = "gin-config" %}
{% set version = 0.3.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a83b7639ae76c276c0380d71d583f151b327a7c37978add314180ec1280a6cc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - enum34  # [py<3]
    - python
    - six >=1.10.0

test:
  imports:
    - gin
    - gin.testdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/gin-config
  summary: 'Gin-Config: A lightweight configuration library for Python'
  dev_url: https://github.com/google/gin-config
  license: Apache-2.0
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
