{% set name = "google-cloud-runtimeconfig" %}
{% set version = 0.30.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02075724535b3d6e1d9a6df8a2340190e195faea2f9e91f48d6ae9006993d636

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3
  run:
    - google-cloud-core >=1.0.3,<2.0dev
    - python !=3.0,!=3.1,!=3.2,!=3.3

test:
  imports:
    - google
    - google.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  summary: Google Cloud RuntimeConfig API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - parthea
