{% set name = "jupyter_nbextensions_configurator" %}
{% set version = 0.4.1 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5e86b5d9d898e1ffb30ebb08e4ad8696999f798fef3ff3262d7b999076e4e83

build:
  number: 0
  noarch: python
  entry_points:
    - jupyter-nbextensions_configurator = jupyter_nbextensions_configurator.application:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - jupyter_contrib_core >=0.3.3
    - jupyter_core
    - notebook >=4.0
    - python
    - pyyaml
    - tornado
    - traitlets

test:
  imports:
    - jupyter_nbextensions_configurator
  commands:
    - pip check
    - jupyter-nbextensions_configurator --help
  requires:
    - pip

about:
  home: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
  summary: jupyter serverextension providing configuration interfaces for nbextensions.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jcb91
