{% set name = "keras-applications" %}
{% set version = 1.0.8 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5579f9a12bcde9748f4a12233925a59b93b73ae6947409ff34aa2ba258189fe5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - h5py
    - numpy >=1.9.1
    - python

test:
  imports:
    - keras_applications
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-applications
  summary: Reference implementations of popular deep learning models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CurtLH
    - jjhelmus
