{% set name = "openapi-spec-validator" %}
{% set version = 0.2.9 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 79381a69b33423ee400ae1624a461dae7725e450e2e306e32f2dd8d16a4d85cb

build:
  number: 0
  entry_points:
    - openapi-spec-validator = openapi_spec_validator.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - jsonschema
    - pathlib2  # [py==27]
    - python
    - pyyaml >=5.1
    - six

test:
  imports:
    - openapi_spec_validator
  commands:
    - pip check
    - openapi-spec-validator --help
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-spec-validator
  summary: OpenAPI 2.0 (aka Swagger) and OpenAPI 3.0.0 spec validator
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rvalieris
