{% set name = "openapi-codec" %}
{% set version = 1.3.2 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bce63289edf53c601ea3683120641407ff6b708803b8954c8a876fe778d2145

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - coreapi >=2.2.0
    - python

test:
  imports:
    - openapi_codec
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/core-api/python-openapi-codec/
  summary: An OpenAPI codec for Core API.
  license: NOASSERTION
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - lsetiawan
    - ocefpaf
