{% set name = "openapi-spec-validator" %}
{% set version = 0.2.8 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e489c7a273284bc78277ac22791482e8058d323b4a265015e9fcddf6a8045bcd

build:
  number: 0
  entry_points:
    - openapi-spec-validator = openapi_spec_validator.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - jsonschema
    - pathlib2  # [py==27]
    - python
    - pyyaml >=5.1
    - six

test:
  imports:
    - openapi_spec_validator
  commands:
    - pip check
    - openapi-spec-validator --help
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-spec-validator
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rvalieris
