{% set name = "os-client-config" %}
{% set version = 2.1.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abc38a351f8c006d34f7ee5f3f648de5e3ecf6455cc5d76cfd889d291cdf3f4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python
  run:
    - openstacksdk >=0.13.0
    - python

test:
  imports:
    - os_client_config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.openstack.org/os-client-config/latest
  summary: OpenStack Client Configuation Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
