{% set name = "oslo.config" %}
{% set version = "8.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oslo.config-{{ version }}.tar.gz
  sha256: 829a6dac59be1880e7b3ae510a7e122a43ba4bfb1d90f59ccefc90d8549d82ad

build:
  number: 0
  skip: true   # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python
  run:
    - debtcollector >=1.2.0
    - importlib-metadata >=1.7.0  # [( py<38 )]
    - netaddr >=0.7.18
    - oslo.i18n >=3.15.3
    - python
    - pyyaml >=3.12
    - requests >=2.18.0
    - rfc3986 >=1.2.0
    - stevedore >=1.20.0

test:
  imports:
    - oslo.config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.openstack.org/oslo.config/latest/
  summary: Oslo Configuration API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
    - tschoonj
