{% set name = "oslo.config" %}
{% set version = 8.2.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 116ff3a7b98b0309b083af7906d99f8c6bea67df5ee03a85e2ac02700dd75d30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python >=3.6
  run:
    - debtcollector >=1.2.0
    - netaddr >=0.7.18
    - oslo.i18n >=3.15.3
    - python >=3.6
    - pyyaml >=3.12
    - requests >=2.18.0
    - rfc3986 >=1.2.0
    - stevedore >=1.20.0

test:
  imports:
    - oslo.config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.openstack.org/oslo.config/latest/
  summary: Oslo Configuration API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
    - tschoonj
