{% set name = "pkgconfig" %}
{% set version = 1.4.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 048c3b457da7b6f686b647ab10bf09e2250e4c50acfe6f215398a8b5e6fcdb52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2
  run:
    - python !=3.0,!=3.1,!=3.2

test:
  imports:
    - pkgconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/matze/pkgconfig
  summary: Interface Python with pkg-config
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
