"{% set name = \"pkgconfig\" %}\n{% set version = 1.4.0 %}\n\n\npackage:\n  name:\
\ {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/{{\
\ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: 048c3b457da7b6f686b647ab10bf09e2250e4c50acfe6f215398a8b5e6fcdb52\n\
\nbuild:\n  number: 0\n  noarch: python\n  script: {{ PYTHON }} -m pip install . -vv\n\
\nrequirements:\n  host:\n    - pip\n    - python !=3.0,!=3.1,!=3.2\n  run:\n    -\
\ python !=3.0,!=3.1,!=3.2\n\ntest:\n  imports:\n    - pkgconfig\n  commands:\n  \
\  - pip check\n  requires:\n    - pip\n\nabout:\n  home: http://github.com/matze/pkgconfig\n\
\  summary: Interface Python with pkg-config\n  license: MIT\n  license_file: LICENSE\n\
\nextra:\n  recipe-maintainers:\n    - jakirkham\n    - lbdreyer\n    - ocefpaf\n"
