{% set name = "podman-compose" %}
{% set version = 0.1.5 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/podman-compose-{{ version }}.tar.gz
  sha256: fb229362f188980ea3fbdee2a25d0a2dd6a0b886d925d5213e22e09f1062ebe9

build:
  number: 0
  noarch: python
  entry_points:
    - podman-compose = podman_compose:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml

test:
  imports:
    - podman_compose
  commands:
    - pip check
    - podman-compose --help
  requires:
    - pip

about:
  home: https://github.com/containers/podman-compose
  summary: A script to run docker-compose.yml using podman
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
