{% set name = "prody" %}
{% set version = 1.11 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ProDy-{{ version }}.tar.gz
  sha256: e355f9185640d107516663069b95a0f67d8837cb324a103222c9a42e3c799123

build:
  number: 0
  entry_points:
    - prody=prody.apps:prody_main
    - evol=prody.apps:evol_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - biopython
    - numpy >=1.10
    - pyparsing
    - python
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - prody
    - prody.apps
  commands:
    - pip check
    - prody --help
    - evol --help
  requires:
    - pip

about:
  home: http://www.csb.pitt.edu/ProDy
  summary: A Python Package for Protein Dynamics Analysis
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jamesmkrieger
    - simonbray
