{% set name = "prody" %}
{% set version = 1.10.10 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ProDy-{{ version }}.tar.gz
  sha256: 9c367abea545cd179dbbeafe4746fbcbe1473507fdf9e8e1af487ea73f32e135

build:
  number: 0
  entry_points:
    - prody=prody.apps:prody_main
    - evol=prody.apps:evol_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - prody
    - prody.apps
  commands:
    - pip check
    - prody --help
    - evol --help
  requires:
    - pip

about:
  home: http://www.csb.pitt.edu/ProDy
  summary: A Python Package for Protein Dynamics Analysis
  license: CC0-1.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jamesmkrieger
    - simonbray
