"{% set name = \"prometheus_client\" %}\n{% set version = 0.8.0 %}\n\n\npackage:\n\
\  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/{{\
\ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: c6e6b706833a6bd1fd51711299edee907857be10ece535126a158f911ee80915\n\
\nbuild:\n  number: 0\n  noarch: python\n  script: {{ PYTHON }} -m pip install . -vv\n\
\nrequirements:\n  host:\n    - pip\n    - python\n  run:\n    - python\n\ntest:\n\
\  imports:\n    - prometheus_client\n    - prometheus_client.bridge\n  commands:\n\
\    - pip check\n  requires:\n    - pip\n\nabout:\n  home: https://github.com/prometheus/client_python\n\
\  summary: Python client for the Prometheus monitoring system.\n  license: AFL-2.0\n\
\  license_file: PLEASE_ADD_LICENSE_FILE\n\nextra:\n  recipe-maintainers:\n    - jessicaaustin\n\
\    - kwilcox\n    - ocefpaf\n"
