{% set name = "pytest-fixture-config" %}
{% set version = 1.7.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41a17417721f6862ce6b40e3280fddd8e1659b2c306ec46b237d7021fec5218e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-git
  run:
    - pytest
    - python

test:
  imports:
    - pytest_fixture_config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manahl/pytest-plugins
  summary: Fixture configuration utils for py.test
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcfr
