{% set name = "quart-openapi" %}
{% set version = 1.3.8 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b55412baee7499c87843347879bfabdad25a5acfae3f28bc00155e25c9e19a53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - jsonschema ==2.6.0
    - python >=3.6
    - quart >=0.5.0

test:
  imports:
    - quart_openapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/factset/quart-openapi
  summary: Framework for Quart to add swagger generation to routes and restful resources
  license: MIT
  license_file: .eggs/pytest_runner-5.2-py3.7.egg/EGG-INFO/LICENSE

extra:
  recipe-maintainers:
    - maxyme
