{% set name = "seed-isort-config" %}
{% set version = 2.2.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be4cfef8f9a3fe8ea1817069c6b624538ac0b429636ec746edeb27e98ed628c8

build:
  number: 0
  noarch: python
  entry_points:
    - seed-isort-config=seed_isort_config:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aspy.refactor-imports
    - python >=3.6

test:
  imports:
    - seed_isort_config
  commands:
    - pip check
    - seed-isort-config --help
  requires:
    - pip

about:
  home: https://github.com/asottile/seed-isort-config
  summary: Statically populate the `known_third_party` `isort` setting.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scopatz
