{% set name = "singularity-compose" %}
{% set version = 0.0.20 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3b31469ad4df61cfbfc36862f40ecb5356a5a176062be85624aaf8858d30bd2

build:
  number: 0
  noarch: python
  entry_points:
    - singularity-compose=scompose.client:start
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - pyaml >=5.1.1
    - python
    - spython >=0.0.77

test:
  imports:
    - scompose
    - scompose.client
  commands:
    - pip check
    - singularity-compose --help
  requires:
    - pip

about:
  home: http://www.github.com/singularityhub/singularity-compose
  summary: simple orchestration for singularity containers
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vsoch
