{% set name = "sphinxcontrib-openapi" %}
{% set version = 0.7.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c1bd10d7653912c59a42f727c62cbb7b75f7905ddd9ccc477ebfd1bc69f0cf3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm >=1.15
  run:
    - jsonschema >=2.5.1
    - m2r >=0.2
    - python >=3.6
    - pyyaml >=3.12
    - sphinx >=2.0
    - sphinxcontrib-httpdomain >=1.5.0

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.openapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/openapi
  summary: OpenAPI (fka Swagger) spec renderer for Sphinx
  dev_url: https://github.com/sphinx-contrib/openapi
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
