{% set name = "swagger-ui-bundle" %}
{% set version = 0.0.6 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5373b683487b1b914dccd23bcd9a3016afa2c2d1cda10f8713c0a9af0f91dd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flake8
    - pip
    - pytest-runner
    - python
  run:
    - jinja2 >=2.0
    - python

test:
  imports:
    - swagger_ui_bundle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dtkav/swagger_ui_bundle
  summary: swagger_ui_bundle - swagger-ui files in a pip package
  license: MIT
  license_file: .eggs/flake8-3.8.3-py3.7.egg/EGG-INFO/LICENSE

extra:
  recipe-maintainers:
    - msarahan
