{% set name = "swagger-spec-validator" %}
{% set version = 2.7.2 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb8a140c9c5d7d061d465416f156f432a92aa1a812b9c04f44e66c1568f13811

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - jsonschema
    - python
    - pyyaml
    - six

test:
  imports:
    - swagger_spec_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/Yelp/swagger_spec_validator
  summary: Validation of Swagger specifications
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rvalieris
