{% set name = "swagger-spec-validator" %}
{% set version = 2.7.3 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4f23ee4dbd52bfcde90b1144dde22304add6260e9f29252e9fd7814c9b8fd16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - jsonschema
    - python
    - pyyaml
    - six

test:
  imports:
    - swagger_spec_validator
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/Yelp/swagger_spec_validator
  summary: Validation of Swagger specifications
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rvalieris
