{% set name = "zconfig" %}
{% set version = 3.5.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a094e492ac31025f5b5a58b32a7c7f03e2e2899c8beb4c1601ea00653bf3ea68

build:
  number: 0
  noarch: python
  entry_points:
    - zconfig = ZConfig.validator:main
    - zconfig_schema2html = ZConfig.schema2html:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ZConfig
    - ZConfig.components
  commands:
    - pip check
    - zconfig --help
    - zconfig_schema2html --help
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/ZConfig/
  summary: Structured Configuration Library
  license: ZPL-2.1
  license_file: COPYRIGHT.txt

extra:
  recipe-maintainers:
    - pmlandwehr
